# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "bounties", :force => true do |t|
    t.column "bitch_id", :integer
    t.column "pwner_id", :integer
  end

  create_table "payout_structures", :force => true do |t|
    t.column "num_players", :integer
  end

  create_table "payouts", :force => true do |t|
    t.column "place",               :integer
    t.column "points",              :integer
    t.column "money",               :integer
    t.column "payout_structure_id", :integer
  end

  create_table "players", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name",  :string
  end

  create_table "results", :force => true do |t|
    t.column "player_id", :integer
    t.column "payout_id", :integer
    t.column "fee_paid",  :boolean
  end

  create_table "series", :force => true do |t|
    t.column "series_name", :string
    t.column "is_complete", :boolean, :default => false
  end

  create_table "tournaments", :force => true do |t|
    t.column "date",      :datetime
    t.column "series_id", :integer
  end

end
